import { useEffect, useState } from 'react'
import './public-lp.css'

function formatNumber(value) { return Number(value || 0).toLocaleString('id-ID') }
function formatMoney(value) { return `$${Number(value || 0).toFixed(2)}` }

export default function PublicLp() {
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true); const [unlocking, setUnlocking] = useState(false); const [offerLimited, setOfferLimited] = useState(false)
  useEffect(() => { let mounted = true; const slug = window.location.pathname.split('/').filter(Boolean).pop() || ''; fetch(`/api/lp/${encodeURIComponent(slug)}`, { headers: { Accept: 'application/json' } }).then(async r => { const b = await r.json().catch(() => ({})); if (!r.ok) throw new Error(b.error || 'Dashboard tidak dapat dimuat.'); return b }).then(b => { if (mounted) setData(b) }).catch(e => { if (mounted) setError(e.message) }).finally(() => { if (mounted) setLoading(false) }); return () => { mounted = false } }, [])
  async function unlock() { if (!data?.offer?.link || unlocking || offerLimited) return; setUnlocking(true); setNotice(''); try { const slug = window.location.pathname.split('/').filter(Boolean).pop() || ''; const r = await fetch(`/api/lp/${encodeURIComponent(slug)}`, { method: 'POST', headers: { Accept: 'application/json' } }); const b = await r.json().catch(() => ({})); if (!r.ok || !b.allowed) { setOfferLimited(true); throw new Error(b.reason || b.error || 'Akses ditolak.'); } window.open(b.link, '_blank', 'noopener,noreferrer'); setNotice(`Akses berhasil. Sisa batas: ${b.remainingHourly} klik/jam dan ${b.remainingIpDaily} klik/IP/hari.`) } catch (e) { setNotice(e.message) } finally { setUnlocking(false) } }
  if (loading) return <main className="public-lp-page"><section className="public-lp-card"><div className="public-brand">DollarRise</div><p>Memuat dashboard...</p></section></main>
  if (error) return <main className="public-lp-page"><section className="public-lp-card"><div className="public-brand">DollarRise</div><h1>Dashboard tidak tersedia</h1><p>{error}</p></section></main>
  const stats = data?.stats || {}
  return <main className="public-lp-page"><section className="public-lp-card"><div className="public-brand">DollarRise</div><p className="public-eyebrow">EXCLUSIVE DASHBOARD</p><h1>{data.user.username}</h1><div className="public-offer"><p className="public-offer-label">OFFER</p><h2>{data.offer.title || 'Exclusive Offer'}</h2><button className={`public-unlock${offerLimited ? ' public-unlock-limited' : ''}`} onClick={unlock} disabled={unlocking || offerLimited}>{offerLimited ? '🔒 LIMIT TERCAPAI' : unlocking ? 'MEMPROSES...' : '🔒 UNLOCK EXCLUSIVE ACCESS'}</button>{notice && <p className="public-notice">{notice}</p>}</div><div className="public-stats"><div className="public-stats-title">STATISTIK ADSTERRA</div><div className="public-stat-grid"><div><span>Impressions</span><strong>{formatNumber(stats.impressions)}</strong></div><div><span>Clicks</span><strong>{formatNumber(stats.clicks)}</strong></div><div><span>CTR</span><strong>{Number(stats.ctr || 0).toFixed(2)}%</strong></div><div><span>CPM</span><strong>{formatMoney(stats.cpm)}</strong></div><div><span>Revenue</span><strong>{formatMoney(stats.revenue)}</strong></div></div>{stats.updatedAt && <p className="public-updated">Terakhir diperbarui: {new Date(stats.updatedAt).toLocaleString('id-ID')}</p>}</div></section></main>
}
